import makeStyles from "@material-ui/core/styles/makeStyles";

export default makeStyles({
  cardDetailsContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    width: "42vw",
    marginTop: "5vh",
  },
  paymentContainer: {
    marginBlock: "5vh",
  },
  cardDetailsTypo: {
    fontWeight: 400,
    fontSize: "24px",
    lineHeight: "38px",
    display: "flex",
    alignItems: "center",
    color: "#131821",
  },
  cardDetailsInputContainer: {
    background: "#F1F4FC",
    borderRadius: "8px",
    padding: "1rem 1.5rem",
    marginTop: "20px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    width: "inherit",
  },
  cardDetailsInput: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    padding: "0px",
    gap: "16px",
    width: "-webkit-fill-available",
  },
  cardDetailsInputTypo: {
    fontWeight: 450,
    fontSize: "20px",
    lineHeight: "100%",
    display: "flex",
    alignItems: "center",
    color: "#131821",
    width: "inherit",
  },
  cardDetailsInputField: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "25px 24px",
    gap: "80px",
    width: "-webkit-fill-available",
    background: "#FFFFFF",
    border: "2px solid #E2EBF6",
    borderRadius: "32px",
    outline: "none",
    "&::placeholder": {
      fontWeight: 400,
      fontSize: "18px",
      lineHeight: "32px",
      display: "flex",
      alignItems: "center",
      textTransform: "uppercase",
      color: "#8690A3",
    },
  },
  cardPersonalDetail: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "inherit",
    marginTop: "20px",
    gap: "1rem",
  },
  buttonContainer: {
    width: "inherit",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: "3vh",
  },
});
